//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalAssignmentPageObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalAssignmentPageObjects.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio cannot be empty..
        /// </summary>
        internal static string BioError {
            get {
                return ResourceManager.GetString("BioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact link is not displayed..
        /// </summary>
        internal static string ContactLinkError {
            get {
                return ResourceManager.GetString("ContactLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default e-mail inconsistency..
        /// </summary>
        internal static string DefaultEmailError {
            get {
                return ResourceManager.GetString("DefaultEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default password inconsistency..
        /// </summary>
        internal static string DefaultPasswordError {
            get {
                return ResourceManager.GetString("DefaultPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail field is not displayed..
        /// </summary>
        internal static string EmailFieldError {
            get {
                return ResourceManager.GetString("EmailFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields cannot be empty..
        /// </summary>
        internal static string EmptyError {
            get {
                return ResourceManager.GetString("EmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First link is not displayed..
        /// </summary>
        internal static string FirstLinkError {
            get {
                return ResourceManager.GetString("FirstLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading does not contain &apos;{0}&apos;..
        /// </summary>
        internal static string HeadingError {
            get {
                return ResourceManager.GetString("HeadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password / email.
        /// </summary>
        internal static string InvalidCredentialsError {
            get {
                return ResourceManager.GetString("InvalidCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address format is not valid.
        /// </summary>
        internal static string InvalidEmailFormatError {
            get {
                return ResourceManager.GetString("InvalidEmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login button is not displayed..
        /// </summary>
        internal static string LoginButtonError {
            get {
                return ResourceManager.GetString("LoginButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        internal static string LoginFailedError {
            get {
                return ResourceManager.GetString("LoginFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo image is not displayed..
        /// </summary>
        internal static string LogoError {
            get {
                return ResourceManager.GetString("LogoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log out..
        /// </summary>
        internal static string LogoutFailedError {
            get {
                return ResourceManager.GetString("LogoutFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        internal static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address can&apos;t be null.
        /// </summary>
        internal static string NullEmailAddressError {
            get {
                return ResourceManager.GetString("NullEmailAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is not displayed..
        /// </summary>
        internal static string PasswordFieldError {
            get {
                return ResourceManager.GetString("PasswordFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy link is not displayed..
        /// </summary>
        internal static string PrivacyLinkError {
            get {
                return ResourceManager.GetString("PrivacyLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed redirect..
        /// </summary>
        internal static string RedirectError {
            get {
                return ResourceManager.GetString("RedirectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second link is not displayed..
        /// </summary>
        internal static string SecondLinkError {
            get {
                return ResourceManager.GetString("SecondLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms link is not displayed..
        /// </summary>
        internal static string TermsLinkError {
            get {
                return ResourceManager.GetString("TermsLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not contain &apos;{1}&apos;..
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
    }
}
